% Shortcut to add a program header

%Get the document object for the object being edited
docObj = matlab.desktop.editor.getActive;

%Get cursor position (line number and position index)
docLine = docObj.Selection(1);
docInd  = docObj.Selection(2);

newline = sprintf('\n');


%Insert program description
docText = {['%% PROGRAM NAME' newline],...
['%PROGRAM DESCRIPTION' newline],...
['%' newline],...
['%' newline],...
...
...%Insert input/output description
['% INPUTS' newline],...
['%   INPUT1 - ' newline],...
['%   INPUT2 - ' newline],...
['%' newline],...
['% OUTPUTS - ' newline],...
['%   OUTPUT1 - ' newline],...
['%   OUTPUT2 - ' newline],...
['%' newline],...
...
...%Insert example text
['% EXAMPLES' newline],...
['%' newline],...
['%   EXAMPLE1' newline],...
['%' newline],...
['%' newline],...
['%   EXAMPLE2' newline],...
['%' newline],...
['%' newline],...
['%' newline],...
...
...%Dependencies
['% DEPENDENCIES' newline],...
['%   Other m-files required: none' newline],...
['%   Subfunctions: none' newline],...
['%   MAT-files required: none' newline],...
...
['%' newline],...
['%   See also: OTHER_FUNCTION_NAME' newline],...
['%' newline],...
['%' newline],...
['%' newline],...
...
...%Insert author information
['% Author: Charles Fieseler' newline],...
['% University of Washington, Dept. of Physics' newline],...
['% Email address: charles.fieseler@gmail.com' newline],...
['% Website: coming soon' newline],...
['% Created: ' date newline],...
[newline],...
[newline],...
...
...%Begin code
['%========================================' newline],...
['%% SECTION 1' newline],...
['%========================================' newline],...
[newline],...
[newline],...
[newline],...
...
['%========================================' newline],...
['%% SECTION 2' newline],...
['%========================================' newline],...
[newline],...
[newline],...
[newline],...
...
['%========================================' newline],...
['%% Private functions' newline],...
['%========================================' newline],...
[newline],...
[newline],...
[newline]};


% Actually insert the text
for j = 1:length(docText)
    docObj.insertTextAtPositionInLine(docText{j},...
        docLine+j-1,docInd);
end

%Clean up
%clear docLine docObj docInd
