function [] = program_header()
% Shortcut to add a program header, of the same format as this header
%
%
% INPUTS
%   INPUT1 - 
%   INPUT2 - 
%
% OUTPUTS - 
%   OUTPUT1 - 
%   OUTPUT2 - 
%
% EXAMPLES
%
%   EXAMPLE1
%
%
%   EXAMPLE2
%
%
%
% Dependencies
%   Other m-files required: 
%   Subfunctions: 
%   MAT-files required: 
%
%   See also: OTHER_FUNCTION_NAME
%
%
%
% Author: Charles Fieseler
% University of Washington, Dept. of Physics
% Email address: charles.fieseler@gmail.com
% Website: coming soon
% Created: 17-Oct-2016


%========================================


%% SECTION 1

%Get the document object for the object being edited
docObj = matlab.desktop.editor.getActive;

%Get cursor position (line number and position index)
docLine = docObj.Selection(1);
docInd  = docObj.Selection(2);

newline = sprintf('\n');


%Insert program description
docText = {['%% PROGRAM NAME' newline],...
['%PROGRAM DESCRIPTION' newline],...
['%' newline],...
['%' newline],...
...
['% INPUTS' newline],...
['%   INPUT1 - ' newline],...
['%   INPUT2 - ' newline],...
['%' newline],...
['% OUTPUTS - ' newline],...
['%   OUTPUT1 - ' newline],...
['%   OUTPUT2 - ' newline],...
['%' newline],...
...
['% EXAMPLES' newline],...
['%' newline],...
['%   EXAMPLE1' newline],...
['%' newline],...
['%' newline],...
['%   EXAMPLE2' newline],...
['%' newline],...
['%' newline],...
['%' newline],...
...
['% Dependencies' newline],...
['%   .m files, .mat files, and MATLAB products required: ' newline],...
...%['%   Subfunctions: ' newline],...
...%['%   MAT-files required: ' newline],...
...
['%' newline],...
['%   See also: OTHER_FUNCTION_NAME' newline],...
['%' newline],...
['%' newline],...
['%' newline],...
...
['% Author: Charles Fieseler' newline],...
['% University of Washington, Dept. of Physics' newline],...
['% Email address: charles.fieseler@gmail.com' newline],...
['% Website: coming soon' newline],...
['% Created: ' date newline],...
['%========================================' newline]};


% Actually insert the text
for j = 1:length(docText)
    docObj.insertTextAtPositionInLine(docText{j},...
        docLine+j-1,docInd);
end

% %Add some sections to get started
% add_section();
% add_section();
% add_section('Private Functions');

end